const img1 =
  "https://res.cloudinary.com/dmxltdk64/image/upload/v1726918435/property-sec/background1_wt1sth.png";
const img2 =
  "https://res.cloudinary.com/dmxltdk64/image/upload/v1726918430/property-sec/bg2-desktop_gzijab.png";
const img3 =
  "https://res.cloudinary.com/dmxltdk64/image/upload/v1726918438/property-sec/bg4-desktop_ldiomf.png";

export const mockProperties = [
  {
    id: 1,
    name: "4 BEDROOM SEMI-DETACHED DUPLEX",
    price: "$328,000,0000",
    toilet: 4,
    bed: 4,
    bath: 4,
    address: "Ikate Lekki, Lagos",
    image: img1,
  },
  {
    id: 2,
    name: "4 BEDROOM SEMI-DETACHED DUPLEX",
    price: "$328,000,0000",
    toilet: 4,
    bed: 4,
    bath: 4,
    address: "Ikate Lekki, Lagos",
    image: img2,
  },
  {
    id: 3,
    name: "4 BEDROOM SEMI-DETACHED DUPLEX",
    price: "$328,000,0000",
    toilet: 4,
    bed: 4,
    bath: 4,
    address: "Ikate Lekki, Lagos",
    image: img3,
  },
  {
    id: 4,
    name: "4 BEDROOM SEMI-DETACHED DUPLEX",
    price: "$328,000,0000",
    toilet: 4,
    bed: 4,
    bath: 4,
    address: "Ikate Lekki, Lagos",
    image: img1,
  },
  {
    id: 5,
    name: "4 BEDROOM SEMI-DETACHED DUPLEX",
    price: "$328,000,0000",
    toilet: 4,
    bed: 4,
    bath: 4,
    address: "Ikate Lekki, Lagos",
    image: img2,
  },
  {
    id: 6,
    name: "4 BEDROOM SEMI-DETACHED DUPLEX",
    price: "$328,000,0000",
    toilet: 4,
    bed: 4,
    bath: 4,
    address: "Ikate Lekki, Lagos",
    image: img3,
  },
  {
    id: 7,
    name: "4 BEDROOM SEMI-DETACHED DUPLEX",
    price: "$328,000,0000",
    toilet: 4,
    bed: 4,
    bath: 4,
    address: "Ikate Lekki, Lagos",
    image: img1,
  },
  {
    id: 8,
    name: "4 BEDROOM SEMI-DETACHED DUPLEX",
    price: "$328,000,0000",
    toilet: 4,
    bed: 4,
    bath: 4,
    address: "Ikate Lekki, Lagos",
    image: img2,
  },
  {
    id: 9,
    name: "4 BEDROOM SEMI-DETACHED DUPLEX",
    price: "$328,000,0000",
    toilet: 4,
    bed: 4,
    bath: 4,
    address: "Ikate Lekki, Lagos",
    image: img3,
  },
  {
    id: 10,
    name: "4 BEDROOM SEMI-DETACHED DUPLEX",
    price: "$328,000,0000",
    toilet: 4,
    bed: 4,
    bath: 4,
    address: "Ikate Lekki, Lagos",
    image: img1,
  },
  {
    id: 11,
    name: "4 BEDROOM SEMI-DETACHED DUPLEX",
    price: "$328,000,0000",
    toilet: 4,
    bed: 4,
    bath: 4,
    address: "Ikate Lekki, Lagos",
    image: img2,
  },
  {
    id: 12,
    name: "4 BEDROOM SEMI-DETACHED DUPLEX",
    price: "$328,000,0000",
    toilet: 4,
    bed: 4,
    bath: 4,
    address: "Ikate Lekki, Lagos",
    image: img3,
  },
];
